---
data_naming:
  training: train
  validation: valid
  testing: test
locations:
  nsynth_data_dir: data/nsynth-||DATA||
  nsynth_metadata_file_name: examples.json
  nsynth_audio_dir_name: audio
  features_base_dir: data/features_||TYPE||
  weights_base_dir: model/weights
  log_base_dir: model/logs
nsynth:
  sample_rate: 16000
  max_seconds: 3
librosa:
  spec_windows: 50
  hop_length: 512
training:
  targets:
    - instrument_family_str
    - pitch
  epochs: 200
  batch_size: 256
  early_stop: 10
  weight_file_pattern: weights-improvement-{epoch:02d}-{loss:.4f}.hdf5
